name: Example Workflow

on:
  push:
    branches:
      - master

jobs:
  example-job:
    runs-on: ubuntu-latest

    env:
      MY_VARIABLE: production

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Environment Variable
      run: echo "My environment variable value is ${{ env.MY_VARIABLE }}"
