name: My Workflow

on:
  push:
    branches:
      - master
 
 

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env:
      MY_ENVVARIABLE: ${{ vars.ENVVARIABLE }}

    steps:
      - name: Read a variable
        run: echo "My ENVVARIABLE value is ${{ vars.ENVVARIABLE }}"

      - name: Tell me a secret!
        run: echo "My existing secret is ${{ secrets.API_KEY }}"
      
      - name: Unset secret
        run: echo "My unknown secret is ${{ secrets.DOES_NOT_EXIST }}"
      
      - name: Github stuff
        run: echo "My Github repo is called ${{ github.repository }}"
      
      - name: Read an env variable
        run: echo "My ENVVARIABLE value is ${{ env.ENVVARIABLE }} (also accessible as $MY_ENVVARIABLE)"

      - uses: actions/checkout@v2
      - name: Read the env from an external script
        run: |
         chmod +x .github/scripts/custom.sh
         .github/scripts/custom.sh
        shell: bash
  
  top-secret-production:
    runs-on: ubuntu-latest
    environment: production
    env:
      ENVVARIABLE: ${{ vars.ENVVARIABLE }}

    steps:
      - name: Read a variable
        run: echo "My ENVVARIABLE value in the production job is $ENVVARIABLE"
