name: My Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_VARIABLE: "envvariable"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print environment variable
      run: echo "My variable value is $MY_VARIABLE"
