name: Example Workflow

on:
  push:
    branches:
      - master

jobs:
  example-job:
    runs-on: ubuntu-latest

    env:
      MY_VARIABLE: MY_VARIABLE

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Environment Variable
      run: echo "My value---${{ env.MY_VARIABLE }}"

  top-secret-production:
    runs-on: ubuntu-latest
    environment: production
    env:
      MY_ENVVARIABLE: ${{ secrets.MY_VARIABLE }}
      
    steps:
      - name: Read a variable
        run: echo "My MY_ENVVARIABLE value in the production job is ---${{ env.MY_ENVVARIABLE }}"
